<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>SOJO_Calculator</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>SOJO_Calculator.Program</StartupObject>
    <ApplicationIcon>Calculator.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Calculator.ico" />
  </ItemGroup>

</Project>